---
apiVersion: apps/v1
kind: Deployment
/etadata:
  name: ensemble-model
  labels:
    app: ensemble-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ensemble-model
  template:
    metadata:
      labels:
        app: ensemble-model
    spec:
      containers:
        - name: ensemble-model
          image: ensemble-model:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7072
              name: headless-svc
            - containerPort: 8082
              name: web-ui
            - containerPort: 35635
              name: block-manager
          env:
            - name: SPARK_MASTER_URL
              value: spark://spark-master-service:7077
---
apiVersion: v1
kind: Service
metadata:
  name: ensemble-model-service
  labels:
    app: ensemble-model
spec:
  selector:
    app: ensemble-model
  ports:
    - port: 7072
      name: headless-svc
    - port: 8082
      name: web-ui
    - port: 35635
      name: block-manager
